import Foundation
import Testing
@testable import Flightdeck

@Suite("Compaction Warnings & Task Handoff")
struct CompactionHandoffTests {

    @Test("Compaction threshold constant is calibrated to 80%")
    func compactionThresholdValue() {
        #expect(SessionAgg.compactionThreshold == 0.80)
    }

    @Test("isNearCompaction obeys 80% threshold and attribution honesty")
    func isNearCompactionThresholdAndSource() {
        var session = SessionAgg(id: "sess-test-001", project: "Flightdeck")
        session.contextTotalTokens = 200_000
        session.contextTokens = 150_000 // 75%
        session.contextWindowSource = .inferred

        // Under 80%
        #expect(session.contextFraction == 0.75)
        #expect(!session.isNearCompaction)

        // Exactly 80% with inferred window source
        session.contextTokens = 160_000
        #expect(session.contextFraction == 0.80)
        #expect(session.isNearCompaction)

        // Above 80% with statusline window source
        session.contextTokens = 185_000 // 92.5%
        session.contextWindowSource = .statusline
        #expect(session.isNearCompaction)

        // Attribution Honesty: fallback window source must NOT trigger compaction alarm
        session.contextWindowSource = .fallback
        #expect(!session.isNearCompaction)
    }

    @Test("taskHandoffPrompt generates complete Markdown instructions")
    func taskHandoffPromptFormatting() {
        var session = SessionAgg(id: "sess-handoff-xyz", project: "Flightdeck")
        session.branch = "feat/hud-enhancements"
        session.cwd = "/Users/pawankumar/Projects/Flightdeck"
        session.model = "claude-3-7-sonnet"
        session.aiTitle = "Optimize dev clean targets and cache recovery"
        session.lastPrompt = "Please add homebrew and cargo cache targets."
        session.contextTotalTokens = 200_000
        session.contextTokens = 170_000 // 85%
        session.contextWindowSource = .inferred
        session.liveTotalCost = 4.75
        session.inputTokens = 140_000
        session.outputTokens = 12_000
        session.noteFileModified("Sources/Flightdeck/DevCleaner.swift")
        session.noteFileModified("Sources/Flightdeck/CLI.swift")

        let prompt = session.taskHandoffPrompt

        #expect(prompt.contains("# TASK HANDOFF: FLIGHTDECK"))
        #expect(prompt.contains("Optimize dev clean targets and cache recovery"))
        #expect(prompt.contains("`sess-handoff-xyz`"))
        #expect(prompt.contains("`feat/hud-enhancements`"))
        #expect(prompt.contains("`/Users/pawankumar/Projects/Flightdeck`"))
        #expect(prompt.contains("170,000 / 200,000 (85%) ⚠️ COMPACTION IMMINENT"))
        #expect(prompt.contains("$4.75"))
        #expect(prompt.contains("Sources/Flightdeck/DevCleaner.swift"))
        #expect(prompt.contains("Sources/Flightdeck/CLI.swift"))
        #expect(prompt.contains("Please add homebrew and cargo cache targets."))
        #expect(prompt.contains("Continuation Directives"))
        #expect(prompt.contains("Run `git status -s` and `git diff`"))
        #expect(prompt.contains("Generated by Flightdeck Cockpit Telemetry"))
    }

    @Test("taskHandoffPrompt handles empty file modifications with lastFile fallback")
    func taskHandoffPromptEmptyFilesFallback() {
        var session = SessionAgg(id: "sess-no-files", project: "OmniSearch")
        session.lastFile = "Sources/Omni/SearchIndex.swift"
        session.contextTotalTokens = 200_000
        session.contextTokens = 40_000 // 20%
        session.contextWindowSource = .inferred

        let prompt = session.taskHandoffPrompt

        #expect(prompt.contains("# TASK HANDOFF: OMNISEARCH"))
        #expect(prompt.contains("`Sources/Omni/SearchIndex.swift` (active file)"))
        #expect(!prompt.contains("COMPACTION IMMINENT"))
    }

    @Test("taskHandoffPrompt respects redactor when presentation mode is active")
    func taskHandoffPromptRedacted() {
        var session = SessionAgg(id: "sess-redacted-123", project: "SecretProject")
        session.branch = "feature/top-secret"
        session.contextTotalTokens = 200_000
        session.contextTokens = 50_000
        session.contextWindowSource = .inferred

        var redactor = Redactor()
        redactor.isEnabled = true
        let redactedSession = session.redacted(by: redactor)

        let prompt = redactedSession.taskHandoffPrompt

        #expect(!prompt.contains("SecretProject"))
        #expect(!prompt.contains("feature/top-secret"))
        #expect(prompt.contains("PROJECT-"))
        #expect(prompt.contains("feature/branch"))
    }
}
